<?php

namespace AppBundle\Repository;

/**
 * AccountMoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountMoveRepository extends \Doctrine\ORM\EntityRepository
{
}
