<?php

namespace AppBundle\Repository;

/**
 * NotaryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
