<?php

namespace AppBundle\Repository;

/**
 * NotaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaryRepository extends \Doctrine\ORM\EntityRepository {

    public function getAllDql() {
        $qb = $this->createQueryBuilder('a');
        $qb->leftJoin('a.registro', 'r');
        $query = $qb->getQuery();

        return $query;
    }

    public function getAllBalaneOfAlTransaccionOfAllNotaries() {

        $sql = "SELECT
                p.id,
                p.first_name,
                p.last_name,
                SUM(if(t.transaction_type=2,ammount,0)) as credit,
                SUM(if(t.transaction_type=1,ammount,0)) as debit,
                SUM(if(t.transaction_type=2,ammount,0))-SUM(if(t.transaction_type=1,ammount,0)) as saldo

                FROM cecat.notary n
                left join cecat.person p on (p.id = n.id)
                left join cecat.transaction t on (t.notary = n.id)
                group by n.id";

        $qb = $this->createQueryBuilder('n');
        $qb->select('n.id,
        n.first_name,
        n.last_name,
        SUM(if(t.transaction_type = 2, ammount, 0)) as credit,
        SUM(if(t.transaction_type = 1, ammount, 0)) as debit,
        SUM(if(t.transaction_type = 2, ammount, 0))-SUM(if(t.transaction_type = 1, ammount, 0)) as saldo')


        ;
        
        $this->createNativeNamedQuery($sql);
    }

}
